import { useState, useRef } from "react";
import { useNavigate, useLocation } from "react-router";
import svgPaths from "../../imports/svg-9ok0hmg33j";
import { MobileContainer } from "../components/MobileContainer";

export function TwoStepVerificationPage() {
  const navigate = useNavigate();
  const location = useLocation();
  
  // Kinukuha natin ang email at password na pinasa galing sa Login Page
  const { email, password } = location.state || {};

  const [codes, setCodes] = useState(["", "", "", "", "", ""]);
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);
  const [errorMsg, setErrorMsg] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleCodeChange = (index: number, value: string) => {
    if (value.length > 1) return;
    
    const newCodes = [...codes];
    newCodes[index] = value;
    setCodes(newCodes);
    setErrorMsg(""); // Para mawala ang error message kapag nag-type ulit

    // Auto-focus sa susunod na input box
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === "Backspace" && !codes[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handleConfirm = async () => {
    const code = codes.join("");
    
    // Safety check kung sakaling ni-refresh ng user ang page at nawala ang state
    if (!email || !password) {
      setErrorMsg("Session expired. Please log in again.");
      setTimeout(() => navigate("/login"), 2000);
      return;
    }

    if (code.length === 6) {
      setIsLoading(true);
      
      try {
        const response = await fetch("http://localhost:3000/auth/login", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          // Ipapasa natin ulit ang email at password kasama ng 6-digit code
          body: JSON.stringify({ email, password, code }),
        });

        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.message || "Invalid or expired 2FA code.");
        }

        // Kapag tama ang code, i-save ang token at pumunta sa dashboard
        if (data.access_token) {
          localStorage.setItem("access_token", data.access_token);
          navigate("/dashboard");
        }
      } catch (error: any) {
        setErrorMsg(error.message);
        // I-clear ang boxes kapag nagka-error para madali mag-type ulit
        setCodes(["", "", "", "", "", ""]);
        inputRefs.current[0]?.focus();
      } finally {
        setIsLoading(false);
      }
    } else {
      setErrorMsg("Please enter all 6 digits.");
    }
  };


  return (
    <MobileContainer>
      <div className="bg-white relative size-full flex flex-col" data-name="Two Step Verification">
        {/* Header with Back Button */}
        <div className="relative flex items-center justify-center pt-[57px] px-6">
          <button
            onClick={() => navigate(-1)}
            className="absolute left-6 h-[18px] w-[10px] bg-transparent border-none cursor-pointer p-0"
          >
            <svg className="block size-full" fill="none" preserveAspectRatio="none" viewBox="0 0 10 18">
              <path
                clipRule="evenodd"
                d={svgPaths.p42a1500}
                fill="black"
                fillOpacity="0.7"
                fillRule="evenodd"
              />
            </svg>
          </button>
        </div>

        {/* Content Container */}
        <div className="flex-1 flex flex-col items-center px-6 pt-20">
          <p className="font-['Montserrat:Bold',sans-serif] font-bold text-[#1e1e1e] text-[24px] leading-[19.098px] mb-6 text-center">
            Two Step Verification
          </p>

          <p className="font-['Open_Sans:Regular',sans-serif] font-normal text-[#989898] text-[14px] text-center leading-[24px] max-w-[340px] mb-12" style={{ fontVariationSettings: "'wdth' 100" }}>
            Enter the six digit code generated by your authentication app.
          </p>

          {/* Six Digit Input */}
          <div className="flex gap-[10px] justify-center w-full mb-12">
            {codes.map((code, index) => (
              <div key={index} className="rounded-[10px] size-[50px] border border-[#e1e1e1] flex items-center justify-center">
                <input
                  ref={(el) => {inputRefs.current[index] = el;}}
                  type="text"
                  inputMode="numeric"
                  maxLength={1}
                  value={code}
                  onChange={(e) => handleCodeChange(index, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(index, e)}
                  className="w-full h-full text-center text-[20px] font-semibold border-none outline-none bg-transparent"
                  style={{ caretColor: "#3878c2" }}
                />
              </div>
            ))}
          </div>

          {/* Confirm Button */}
          <div className="w-full max-w-[371px]">
            <button
              onClick={handleConfirm}
              className="bg-gradient-to-r from-[#20a9ea] h-[44px] rounded-[100px] to-[#006c9f] via-[#118cc6] via-[62.019%] w-full cursor-pointer border-none flex items-center justify-center"
            >
              <p className="font-['Poppins:Bold',sans-serif] text-[14px] text-white tracking-[0.1px]">
                Confirm
              </p>
            </button>
          </div>
        </div>
      </div>
    </MobileContainer>
  );
}