import svgPaths from "./svg-9ok0hmg33j";

function Boxes() {
  return (
    <div className="col-1 h-[50px] ml-0 mt-0 relative row-1 w-[312px]" data-name="Boxes">
      <div className="-translate-x-1/2 absolute left-[calc(50%+193px)] rounded-[10px] size-[50px] top-0">
        <div aria-hidden="true" className="absolute border border-[#e1e1e1] border-solid inset-[-0.5px] pointer-events-none rounded-[10.5px]" />
      </div>
      <div className="-translate-x-1/2 absolute left-[calc(50%+131px)] rounded-[10px] size-[50px] top-0">
        <div aria-hidden="true" className="absolute border border-[#e1e1e1] border-solid inset-[-0.5px] pointer-events-none rounded-[10.5px]" />
      </div>
      <div className="-translate-x-1/2 absolute left-[calc(50%+66px)] rounded-[10px] size-[50px] top-0">
        <div aria-hidden="true" className="absolute border border-[#e1e1e1] border-solid inset-[-0.5px] pointer-events-none rounded-[10.5px]" />
      </div>
      <div className="-translate-x-1/2 absolute left-1/2 rounded-[10px] size-[50px] top-0">
        <div aria-hidden="true" className="absolute border border-[#e1e1e1] border-solid inset-[-0.5px] pointer-events-none rounded-[10.5px]" />
      </div>
      <div className="-translate-x-1/2 absolute left-[calc(50%-65px)] rounded-[10px] size-[50px] top-0">
        <div aria-hidden="true" className="absolute border border-[#e1e1e1] border-solid inset-[-0.5px] pointer-events-none rounded-[10.5px]" />
      </div>
      <div className="-translate-x-1/2 absolute left-[calc(50%-131px)] rounded-[10px] size-[50px] top-0">
        <div aria-hidden="true" className="absolute border border-[#e1e1e1] border-solid inset-[-0.5px] pointer-events-none rounded-[10.5px]" />
      </div>
    </div>
  );
}

function SixDigit() {
  return (
    <div className="grid-cols-[max-content] grid-rows-[max-content] inline-grid leading-[0] place-items-start relative shrink-0" data-name="Six Digit">
      <Boxes />
    </div>
  );
}

function SixDigitConfirmation() {
  return (
    <div className="absolute content-stretch flex items-center justify-between left-[28px] top-[264px] w-[374px]" data-name="Six Digit Confirmation">
      <SixDigit />
    </div>
  );
}

function TwoStepVerification1() {
  return (
    <div className="-translate-x-1/2 absolute contents left-[calc(50%-1px)] text-center top-[149px]" data-name="Two Step Verification">
      <p className="-translate-x-1/2 absolute font-['Open_Sans:Regular',sans-serif] font-normal leading-[24px] left-[calc(50%-1px)] text-[#989898] text-[14px] top-[185.07px] w-[340px]" style={{ fontVariationSettings: "'wdth' 100" }}>
        Enter the six digit code generated by your authentication app.
      </p>
      <p className="-translate-x-1/2 absolute font-['Montserrat:Bold',sans-serif] font-bold leading-[19.098px] left-[calc(50%-1px)] text-[#1e1e1e] text-[24px] top-[149px] whitespace-nowrap">Two Step Verification</p>
    </div>
  );
}

function StateLayer() {
  return (
    <div className="flex-[1_0_0] min-h-px min-w-px relative w-full" data-name="state-layer">
      <div className="flex flex-row items-center justify-center size-full">
        <div className="content-stretch flex items-center justify-center px-[24px] py-[10px] relative size-full">
          <div className="flex flex-col font-['Poppins:Bold',sans-serif] justify-center leading-[0] not-italic relative shrink-0 text-[14px] text-center text-white tracking-[0.1px] whitespace-nowrap">
            <p className="leading-[20px]">Confirm</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function TwoStepVerification() {
  return (
    <div className="bg-white relative size-full" data-name="Two Step Verification">
      <SixDigitConfirmation />
      <TwoStepVerification1 />
      <div className="-translate-x-1/2 -translate-y-1/2 absolute h-[18px] left-[calc(50%-192px)] top-[calc(50%-415px)] w-[10px]" data-name="Return Symbol">
        <svg className="absolute block size-full" fill="none" preserveAspectRatio="none" viewBox="0 0 10 18">
          <path clipRule="evenodd" d={svgPaths.p42a1500} fill="var(--fill-0, black)" fillOpacity="0.7" fillRule="evenodd" id="Return Symbol" />
        </svg>
      </div>
      <div className="absolute bg-gradient-to-r content-stretch cursor-pointer flex flex-col from-[#20a9ea] h-[44px] items-center justify-center left-[34px] overflow-clip rounded-[100px] to-[#006c9f] top-[375px] via-[#118cc6] via-[62.019%] w-[371px]" data-name="Confirm">
        <StateLayer />
      </div>
    </div>
  );
}